# Generated by Django 2.1.5 on 2019-03-01 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_accident'),
    ]

    operations = [
        migrations.CreateModel(
            name='acmodels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_acmodels', models.CharField(max_length=100, verbose_name='基本型号')),
                ('expanded_acmodels', models.CharField(max_length=100, verbose_name='扩展型号')),
            ],
        ),
        migrations.AlterField(
            model_name='accident',
            name='content',
            field=models.TextField(verbose_name='事件描述'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='date',
            field=models.DateField(verbose_name='发生时间'),
        ),
        migrations.AddField(
            model_name='accident',
            name='acmodels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.acmodels'),
            preserve_default=False,
        ),
    ]
