# Generated by Django 2.1.5 on 2019-06-25 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='terms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='概念')),
                ('content', models.TextField(verbose_name='概念说明')),
            ],
        ),
        migrations.AddField(
            model_name='acmodels',
            name='if_intra_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terms',
            name='acmodels',
            field=models.ForeignKey(limit_choices_to={'if_intra_ac': True}, on_delete=django.db.models.deletion.CASCADE, to='blog.acmodels'),
        ),
    ]
