# Generated by Django 2.2.2 on 2019-06-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190626_1005'),
        ('blog', '0005_auto_20190625_0746'),
    ]

    operations = [
    ]
